//go:build !test
// Code generated by mockery v2.20.2. DO NOT EDIT.

package kneu

import mock "github.com/stretchr/testify/mock"

// MockApiClientInterface is an autogenerated mock type for the ApiClientInterface type
type MockApiClientInterface struct {
	mock.Mock
}

// GetUserMe provides a mock function with given fields:
func (_m *MockApiClientInterface) GetUserMe() (UserMeResponse, error) {
	ret := _m.Called()

	var r0 UserMeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (UserMeResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() UserMeResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(UserMeResponse)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockApiClientInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockApiClientInterface creates a new instance of MockApiClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockApiClientInterface(t mockConstructorTestingTNewMockApiClientInterface) *MockApiClientInterface {
	mock := &MockApiClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
