// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	kneu "github.com/berejant/go-kneu"
	mock "github.com/stretchr/testify/mock"
)

// OauthClientInterface is an autogenerated mock type for the OauthClientInterface type
type OauthClientInterface struct {
	mock.Mock
}

// GetOauthToken provides a mock function with given fields: redirectUri, code
func (_m *OauthClientInterface) GetOauthToken(redirectUri string, code string) (kneu.OauthTokenResponse, error) {
	ret := _m.Called(redirectUri, code)

	if len(ret) == 0 {
		panic("no return value specified for GetOauthToken")
	}

	var r0 kneu.OauthTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (kneu.OauthTokenResponse, error)); ok {
		return rf(redirectUri, code)
	}
	if rf, ok := ret.Get(0).(func(string, string) kneu.OauthTokenResponse); ok {
		r0 = rf(redirectUri, code)
	} else {
		r0 = ret.Get(0).(kneu.OauthTokenResponse)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(redirectUri, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOauthUrl provides a mock function with given fields: redirectUri, state
func (_m *OauthClientInterface) GetOauthUrl(redirectUri string, state string) string {
	ret := _m.Called(redirectUri, state)

	if len(ret) == 0 {
		panic("no return value specified for GetOauthUrl")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(redirectUri, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewOauthClientInterface creates a new instance of OauthClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOauthClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OauthClientInterface {
	mock := &OauthClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
